image-mapping:
  - compute-nest-registry.cn-hangzhou.cr.aliyuncs.com/computenest-test/busybox:latest
  - compute-nest-registry.cn-hangzhou.cr.aliyuncs.com/computenest-test/valkey/valkey:8
  - compute-nest-registry.cn-hangzhou.cr.aliyuncs.com/computenest-test/mysql:8.0.39
  - compute-nest-registry.cn-hangzhou.cr.aliyuncs.com/computenest-test/infiniflow/ragflow:v0.19.1-slim
  - compute-nest-registry.cn-hangzhou.cr.aliyuncs.com/computenest-test/infiniflow/infinity:v0.6.0-dev3
  - compute-nest-registry.cn-hangzhou.cr.aliyuncs.com/computenest-test/quay.io/minio/minio:RELEASE.2023-12-20T01-00-02Z